name: Build LaTeX document
on: [push]
jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume.tex
            resume_transcript.tex
      - name: Rename resume
        run: (mv resume.pdf Phitchawat_Lukkanathiti_Resume.pdf && mv resume_transcript.pdf Phitchawat_Lukkanathiti_Resume_with_transcript.pdf )
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Phitchawat_Lukkanathiti_Resume
          path: Phitchawat_Lukkanathiti_Resume.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Phitchawat_Lukkanathiti_Resume_with_transcript
          path: Phitchawat_Lukkanathiti_Resume_with_transcript.pdf
      - name: Send Email Notification
        uses: peter-evans/sendgrid-action@v1.0.1
        env:
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          SCRIPT_FILEPATH: ./email.js
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          artifacts: "Phitchawat_Lukkanathiti_Resume*.pdf"
