name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            resume.tex
            resume_transcript.tex
      - name: Rename resume
        run: (mv resume.pdf Phitchawat_Lukkanathiti_Resume.pdf && mv resume_transcript.pdf Phitchawat_Lukkanathiti_Resume_with_transcript.pdf )
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Phitchawat_Lukkanathiti_Resume
          path: Phitchawat_Lukkanathiti_Resume.pdf
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: Phitchawat_Lukkanathiti_Resume_with_transcript
          path: Phitchawat_Lukkanathiti_Resume_with_transcript.pdf
